In [116]:
import torch
import tqdm
from torch.utils.data import Dataset
from torchvision import datasets
from torch import nn
from bokeh.plotting import figure, show, output_notebook
output_notebook()
#import matplotlib.pyplot as plt
import numpy as np


Loading BokehJS ...

In [132]:
class OLS(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear=nn.Linear(2,1,dtype=torch.float64)
    
    def forward(self,x):
        return self.linear(x)
    
    

In [133]:
data = np.genfromtxt("data.csv",delimiter=",",skip_header=1)

OLS(
  (linear): Linear(in_features=2, out_features=1, bias=True)
)
[('linear.weight', Parameter containing:
tensor([[-0.1029,  0.3952]], dtype=torch.float64, requires_grad=True)), ('linear.bias', Parameter containing:
tensor([0.3459], dtype=torch.float64, requires_grad=True))]


In [153]:
model = OLS()
Xt = torch.from_numpy(X)
Yt = torch.from_numpy(Y)
loss_fun = torch.nn.functional.mse_loss
optimizer = torch.optim.SGD(model.parameters(),lr=.01)

print(model)
print(list(model.named_parameters()))

OLS(
  (linear): Linear(in_features=2, out_features=1, bias=True)
)
[('linear.weight', Parameter containing:
tensor([[ 0.3251, -0.3620]], dtype=torch.float64, requires_grad=True)), ('linear.bias', Parameter containing:
tensor([0.0209], dtype=torch.float64, requires_grad=True))]


In [154]:
def train(model, loss_fun, optimizer, Xt, Yt):
    predicted = model(Xt)
    loss = loss_fun(predicted, Yt)

    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

    return loss.item()


In [158]:
losses=[]
for i in tqdm.tqdm(range(1000)):
    l=train(model,loss_fun, optimizer, Xt, Yt)
    losses.append(l)

100%|██████████| 1000/1000 [00:00<00:00, 5653.83it/s]


In [159]:
p=figure(title='Losses')
p.line(x=list(range(len(losses))),y=losses)
show(p)


In [160]:
print(list(model.named_parameters()))
print(loss_fun(model(Xt),Yt))

[('linear.weight', Parameter containing:
tensor([[ 1.7998, -3.4715]], dtype=torch.float64, requires_grad=True)), ('linear.bias', Parameter containing:
tensor([5.9996], dtype=torch.float64, requires_grad=True))]
tensor(1.0372, dtype=torch.float64, grad_fn=<MseLossBackward0>)
