In [51]:
import torch
from torch.utils.data import Dataset
from torchvision import datasets
from torch import nn
from torchvision.transforms import ToTensor
import matplotlib.pyplot as plt
import numpy as np


In [31]:
print(torch.cuda.is_available())

True


In [32]:
print(torch.__version__)

1.13.1.post200


In [33]:
x_data = torch.tensor([[1,2],[3,4]],dtype=torch.float).to("cuda")
y_data = torch.tensor([[3],[4]],dtype=torch.float).to("cuda")

In [34]:
x_data @ y_data

tensor([[11.],
        [25.]], device='cuda:0')

In [35]:
x_data.shape

torch.Size([2, 2])

In [36]:
x_data.dtype

torch.float32

In [37]:
x_data.device

device(type='cuda', index=0)

In [46]:
data = np.genfromtxt("data.csv",delimiter=",",skip_header=1)

In [49]:
data[:20,:]

array([[  0.        ,   9.22345149,   1.62488669,  -0.33204394],
       [  1.        ,  -6.51121434,   0.25676938,   4.16345627],
       [  2.        ,  -3.83393779,   1.78444569,   3.73164655],
       [  3.        ,   0.66749243,   4.46821124,   4.48238703],
       [  4.        ,  -3.69480183,   1.68043926,   4.13410517],
       [  5.        ,  -5.19052443,   0.51019106,   3.50993366],
       [  6.        ,  -7.22411237,   1.86304734,   5.26523737],
       [  7.        ,   2.63926015,   1.08382175,   1.53679798],
       [  8.        , -11.60334428,   0.29769922,   4.89711817],
       [  9.        ,   3.64332842,   1.65082785,   1.62595812],
       [ 10.        ,   5.24125661,   2.83414529,   1.27337066],
       [ 11.        ,  -3.95033813,   3.87389134,   4.66829846],
       [ 12.        , -13.3583552 ,   1.59902074,   6.21598384],
       [ 13.        , -10.93153509,   2.93220304,   6.51100542],
       [ 14.        , -12.43473671,   0.20801005,   5.29286209],
       [ 15.        ,   7

In [50]:
Y = data[:,1].reshape(-1,1)
X = data[:,2:]

In [77]:
class OLS(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear=nn.Linear(2,1,dtype=torch.float64)
    
    def forward(self,x):
        return self.linear(x)
    
    

In [241]:
model = OLS().to("cuda")
print(model)

OLS(
  (linear): Linear(in_features=2, out_features=1, bias=True)
)


In [222]:
Xt = torch.from_numpy(X).to("cuda")


In [90]:
Xt.dtype

torch.float64

In [91]:
model(Xt).shape

torch.Size([75, 1])

In [97]:
for name,param in model.named_parameters():
    print(f"Layer: {name} | Size: {param.size()} | Values : {param[:2]} \n")

Layer: linear.weight | Size: torch.Size([1, 2]) | Values : tensor([[-0.2828, -0.4166]], device='cuda:0', dtype=torch.float64,
       grad_fn=<SliceBackward0>) 

Layer: linear.bias | Size: torch.Size([1]) | Values : tensor([-0.0848], device='cuda:0', dtype=torch.float64,
       grad_fn=<SliceBackward0>) 



In [98]:
Xt @ torch.tensor([[-.2828,-.4166]],dtype=torch.float64,device="cuda").T + torch.tensor([-.0848],device="cuda",dtype=torch.float64)

tensor([[-0.4060],
        [-1.8919],
        [-2.1440],
        [-3.2158],
        [-2.2823],
        [-1.6913],
        [-2.8052],
        [-1.0315],
        [-2.2091],
        [-1.2290],
        [-1.4168],
        [-3.1251],
        [-3.1266],
        [-3.6265],
        [-2.3486],
        [-0.9938],
        [-2.8459],
        [-2.6216],
        [-3.9658],
        [-2.5332],
        [-1.3234],
        [-1.9615],
        [-0.2982],
        [-2.5758],
        [-2.0321],
        [-1.8111],
        [-1.8344],
        [-1.6888],
        [-1.2829],
        [-0.9054],
        [ 0.1721],
        [-1.9870],
        [-1.4317],
        [-5.5515],
        [-2.1672],
        [-0.8389],
        [ 0.6837],
        [-1.2172],
        [-3.1577],
        [-0.4755],
        [-0.6584],
        [-1.7606],
        [-0.7951],
        [-4.0310],
        [-2.2024],
        [-1.7414],
        [-2.8161],
        [-1.1524],
        [-3.7586],
        [-3.2324],
        [-2.2488],
        [-2.2408],
        [-1.

In [96]:
model(Xt)

tensor([[-0.4060],
        [-1.8918],
        [-2.1439],
        [-3.2156],
        [-2.2822],
        [-1.6913],
        [-2.8050],
        [-1.0315],
        [-2.2090],
        [-1.2290],
        [-1.4167],
        [-3.1250],
        [-3.1264],
        [-3.6263],
        [-2.3485],
        [-0.9938],
        [-2.8458],
        [-2.6215],
        [-3.9656],
        [-2.5331],
        [-1.3233],
        [-1.9614],
        [-0.2981],
        [-2.5756],
        [-2.0320],
        [-1.8110],
        [-1.8343],
        [-1.6888],
        [-1.2828],
        [-0.9054],
        [ 0.1720],
        [-1.9869],
        [-1.4317],
        [-5.5513],
        [-2.1671],
        [-0.8389],
        [ 0.6836],
        [-1.2171],
        [-3.1575],
        [-0.4755],
        [-0.6584],
        [-1.7605],
        [-0.7951],
        [-4.0307],
        [-2.2023],
        [-1.7413],
        [-2.8160],
        [-1.1523],
        [-3.7584],
        [-3.2322],
        [-2.2487],
        [-2.2407],
        [-1.

In [100]:
loss = torch.nn.functional.mse_loss(model(Xt),torch.from_numpy(Y).to("cuda"))

In [101]:
loss

tensor(68.8517, device='cuda:0', dtype=torch.float64,
       grad_fn=<MseLossBackward0>)

In [104]:
((Xt @ torch.tensor([[-.2828,-.4166]],dtype=torch.float64,device="cuda").T + torch.tensor([-.0848],device="cuda",dtype=torch.float64) - torch.from_numpy(Y).to("cuda"))**2).mean()

tensor(68.8514, device='cuda:0', dtype=torch.float64)

In [105]:
loss.backward()

In [219]:
Yt = torch.from_numpy(Y).to("cuda")


In [223]:


w.is_leaf



True

In [229]:
learning_rate=.01

In [230]:
w = torch.randn(2,1,dtype=torch.float64,requires_grad=True,device="cuda")
b = torch.randn(1,dtype=torch.float64,requires_grad=True,device="cuda")
z = torch.matmul(Xt,w)+b

In [246]:
loss_fun = torch.nn.functional.mse_loss
optimizer = torch.optim.SGD(model.parameters(),lr=learning_rate)

In [250]:
def train(model, loss_fun, optimizer, Xt, Yt):
    predicted = model(Xt)
    loss = loss_fun(predicted, Yt)

    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

    print(loss.item())


In [257]:
for i in range(10000):
    train(model,loss_fun, optimizer, Xt, Yt)

1.036756144617863
1.036753159242356
1.036750198486535
1.0367472621473661
1.0367443500234916
1.0367414619152135
1.0367385976244814
1.0367357569548767
1.0367329397116023
1.0367301457014666
1.0367273747328711
1.0367246266157975
1.0367219011617959
1.0367191981839683
1.0367165174969593
1.0367138589169411
1.0367112222616035
1.0367086073501386
1.0367060140032303
1.0367034420430392
1.036700891293196
1.036698361578783
1.0366958527263261
1.0366933645637817
1.036690896920525
1.0366884496273387
1.0366860225163994
1.0366836154212702
1.0366812281768853
1.036678860619539
1.0366765125868789
1.036674183917888
1.0366718744528793
1.0366695840334819
1.036667312502631
1.0366650597045584
1.0366628254847778
1.036660609690079
1.0366584121685152
1.0366562327693911
1.0366540713432562
1.036651927741891
1.0366498018182997
1.0366476934266966
1.0366456024225
1.03664352866232
1.0366414720039498
1.0366394323063548
1.0366374094296629
1.0366354032351561
1.0366334135852613
1.0366314403435382
1.0366294833746725
1.0366275

In [260]:
print(list(model.named_parameters()))

[('linear.weight', Parameter containing:
tensor([[ 1.7878, -3.4790]], device='cuda:0', dtype=torch.float64,
       requires_grad=True)), ('linear.bias', Parameter containing:
tensor([6.0608], device='cuda:0', dtype=torch.float64, requires_grad=True))]


In [238]:
train(model, loss, optimizer,Xt,Yt)

TypeError: 'Tensor' object is not callable

In [227]:
print(w.grad)

tensor([[ 11.9444],
        [107.2317]], device='cuda:0', dtype=torch.float64)


In [196]:
import torch

x = torch.ones(5) # input tensor
y = torch.zeros(3)  # expected output
w = torch.randn(5, 3, requires_grad=True,device="cuda")
b = torch.randn(3, requires_grad=True,device="cuda"))
z = torch.matmul(x, w)+b
loss = torch.nn.functional.binary_cross_entropy_with_logits(z, y)

w.is_leaf

True

In [183]:
loss.backward()
print(w.grad)

None


/tmp/ipykernel_14113/292401841.py:2: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at /home/conda/feedstock_root/build_artifacts/pytorch-recipe_1673730874951/work/build/aten/src/ATen/core/TensorBody.h:480.)
  print(w.grad)


In [186]:
z.device

device(type='cuda', index=0)

In [187]:
loss.device

device(type='cuda', index=0)